
import { Phone } from '@/types/phones';

// Export a more extensive set of example phones for testing
export const getExamplePhones = (): Phone[] => [
  {
    id: "example-1",
    ean: "1234567890123",
    title: "Samsung Galaxy S23 Ultra - 256 Go - Noir",
    trademark: "Samsung",
    description: "Galaxy S23 Ultra 5G - écran 6,8\" Dynamic AMOLED 2X - 12 Go RAM - 256 Go - S Pen inclus",
    fullDescription: "Le Galaxy S23 Ultra est doté d'un appareil photo de 200MP pour des prises de vue nocturnes époustouflantes, du S Pen intégré, et d'une batterie qui dure plus d'une journée.",
    price: 899,
    originalPrice: 1199,
    discount: 300,
    image: "https://www.bouyguestelecom.fr/catalogue/image-resize/full/media/catalog/product/v/i/vig-samsung-galaxy-s23-plus-noir-face_2.png",
    additionalImages: [],
    category: "Smartphones",
    merchant: "Samsung Shop",
    condition: "new",
    operatingSystem: "Android",
    color: "Noir",
    storage: "256 Go",
    shipping: "Livraison gratuite",
    installmentPrice: 39,
    installmentMonths: 24,
    promotion: "Galaxy Buds2 Pro OFFERTS",
    isEcoFriendly: true,
    inStock: true,
    rating: 4.8,
    reviewCount: 423,
    productUrl: "https://www.samsung.com/fr/smartphones/galaxy-s23-ultra/"
  },
  {
    id: "example-2",
    ean: "2345678901234",
    title: "iPhone 14 Pro - 256 Go - Violet Intense",
    trademark: "Apple",
    description: "iPhone 14 Pro - écran 6,1\" Super Retina XDR - 256 Go - Dynamic Island - Puce A16 Bionic",
    fullDescription: "L'iPhone 14 Pro introduit Dynamic Island et l'écran toujours activé. Appareil photo 48Mpx pour une résolution 4x supérieure. Détection des accidents. A16 Bionic, la puce de smartphone la plus rapide au monde.",
    price: 1099,
    originalPrice: 1329,
    discount: 230,
    image: "https://www.bouyguestelecom.fr/catalogue/image-resize/full/media/catalog/product/v/i/vig-apple-iphone-14-pro-violet-intense-face.png",
    category: "Smartphones",
    merchant: "Apple Store",
    condition: "new",
    operatingSystem: "iOS",
    color: "Violet Intense",
    storage: "256 Go",
    shipping: "Livraison sous 24h",
    promotion: "",
    rating: 4.9,
    reviewCount: 512,
    inStock: true,
    productUrl: "https://www.apple.com/fr/iphone-14-pro/"
  },
  {
    id: "example-3",
    ean: "3456789012345",
    title: "Google Pixel 7 Pro - 128 Go - Vert Sauge",
    trademark: "Google",
    description: "Pixel 7 Pro - écran 6,7\" QHD+ LTPO OLED 120 Hz - 128 Go - Processeur Google Tensor G2",
    fullDescription: "Le Google Pixel 7 Pro est le smartphone le plus avancé de Google à ce jour. Il est équipé de la puce Google Tensor G2 et du système Titan M2, qui le rendent plus rapide, plus efficace et plus sécurisé.",
    price: 649,
    originalPrice: 899,
    discount: 250,
    image: "https://lh3.googleusercontent.com/uSGjbg5FYWX01alVH1x6s6JZlvl5YS_H9frL0a2-mjMYZHTWAaJqXpVvrOIkSHQkIxEHLX7FDbBz9jv3cGOsUfhbYGaf-zdI",
    category: "Smartphones",
    merchant: "Google Store",
    condition: "new",
    operatingSystem: "Android",
    color: "Vert Sauge",
    storage: "128 Go",
    shipping: "Livraison gratuite",
    rating: 4.6,
    reviewCount: 368,
    inStock: true,
    isEcoFriendly: true,
    productUrl: "https://store.google.com/fr/product/pixel_7_pro"
  },
  {
    id: "example-4",
    ean: "4567890123456",
    title: "Xiaomi 13 - 256 Go - Blanc",
    trademark: "Xiaomi",
    description: "Xiaomi 13 - écran 6,36\" AMOLED 120 Hz - Snapdragon 8 Gen 2 - 256 Go - Co-développé avec Leica",
    price: 699,
    originalPrice: 999,
    discount: 300,
    image: "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-13-2.jpg",
    category: "Smartphones",
    merchant: "Mi Store",
    condition: "new",
    operatingSystem: "Android",
    color: "Blanc",
    storage: "256 Go",
    shipping: "Livraison en 48h",
    installmentPrice: 29,
    installmentMonths: 24,
    rating: 4.5,
    reviewCount: 215,
    inStock: true,
    productUrl: "https://www.mi.com/fr/product/xiaomi-13/"
  },
  {
    id: "example-5",
    ean: "5678901234567",
    title: "iPhone 15 - 128 Go - Noir",
    trademark: "Apple",
    description: "iPhone 15 - écran 6,1\" Super Retina XDR - 128 Go - Puce A16 Bionic",
    price: 799,
    image: "https://www.bouyguestelecom.fr/catalogue/image-resize/full/media/catalog/product/v/i/vig-apple-iphone-15-noir-face.png",
    category: "Smartphones",
    merchant: "Apple Store",
    condition: "new",
    operatingSystem: "iOS",
    color: "Noir",
    storage: "128 Go",
    shipping: "Livraison gratuite",
    rating: 4.7,
    reviewCount: 432,
    isEcoFriendly: true,
    inStock: true,
    productUrl: "https://www.apple.com/fr/iphone-15/"
  },
  {
    id: "example-6",
    ean: "6789012345678",
    title: "Samsung Galaxy S25 Plus - 256 Go - Bleu Nuit",
    trademark: "Samsung",
    description: "Galaxy S25 Plus - écran 6,7\" Dynamic AMOLED 2X - 12 Go RAM - 256 Go",
    price: 999,
    originalPrice: 1199,
    discount: 200,
    image: "https://www.bouyguestelecom.fr/catalogue/image-resize/full/media/catalog/product/v/i/vig-samsung-galaxy-s25-plus-bleu-nuit-et-tab-s6-lite-offerte.png",
    category: "Smartphones",
    merchant: "Samsung Shop",
    condition: "new",
    operatingSystem: "Android",
    color: "Bleu Nuit",
    storage: "256 Go",
    shipping: "Livraison gratuite",
    installmentPrice: 33,
    installmentMonths: 24,
    rating: 4.8,
    reviewCount: 187,
    inStock: true,
    promotion: "Galaxy Tab S6 Lite OFFERTE",
    productUrl: "https://www.samsung.com/fr/smartphones/galaxy-s25-plus/"
  },
  {
    id: "example-7",
    ean: "7890123456789",
    title: "OnePlus 11 - 256 Go - Noir",
    trademark: "OnePlus",
    description: "OnePlus 11 5G - écran 6,7\" AMOLED LTPO3 120 Hz - Snapdragon 8 Gen 2 - 256 Go",
    price: 699,
    originalPrice: 919,
    discount: 220,
    image: "https://oasis.opstatics.com/content/dam/oasis/page/2023/operation/mar/0306/EU-IN_green_pdp_carousel_2_img.jpg",
    category: "Smartphones",
    merchant: "OnePlus Store",
    condition: "new",
    operatingSystem: "Android",
    color: "Noir",
    storage: "256 Go",
    shipping: "Livraison sous 48h",
    rating: 4.5,
    reviewCount: 156,
    inStock: true,
    productUrl: "https://www.oneplus.com/fr/oneplus-11"
  },
  {
    id: "example-8",
    ean: "8901234567890",
    title: "iPhone 16 Pro - 256 Go - Titane Sable",
    trademark: "Apple",
    description: "iPhone 16 Pro - écran 6,3\" Super Retina XDR Always-On - Puce A18 Pro - 256 Go",
    price: 1199,
    originalPrice: 1399,
    discount: 200,
    image: "https://www.bouyguestelecom.fr/catalogue/image-resize/full/media/catalog/product/v/i/vig-apple-iphone-16-pro-titane-sable-face_1.png",
    category: "Smartphones",
    merchant: "Apple Store",
    condition: "new",
    operatingSystem: "iOS",
    color: "Titane Sable",
    storage: "256 Go",
    shipping: "Livraison gratuite",
    rating: 4.9,
    reviewCount: 142,
    isEcoFriendly: true,
    inStock: true,
    productUrl: "https://www.apple.com/fr/iphone-16-pro/"
  },
  {
    id: "example-9",
    ean: "9012345678901",
    title: "Samsung Galaxy A26 5G - 128 Go - Noir",
    trademark: "Samsung",
    description: "Galaxy A26 5G - écran 6,5\" Super AMOLED 120 Hz - 128 Go - Batterie 5000 mAh",
    price: 299,
    originalPrice: 399,
    discount: 100,
    image: "https://www.bouyguestelecom.fr/catalogue/image-resize/full/media/catalog/product/v/i/vig-samsung-galaxy-a26-5g-noir-face.png",
    category: "Smartphones",
    merchant: "Boulanger",
    condition: "new",
    operatingSystem: "Android",
    color: "Noir",
    storage: "128 Go",
    shipping: "Livraison gratuite",
    installmentPrice: 12,
    installmentMonths: 24,
    rating: 4.4,
    reviewCount: 278,
    inStock: true,
    productUrl: "https://www.samsung.com/fr/smartphones/galaxy-a/galaxy-a26-5g/"
  },
  {
    id: "example-10",
    ean: "0123456789012",
    title: "iPhone 15 Plus - 128 Go - Noir",
    trademark: "Apple",
    description: "iPhone 15 Plus - écran 6,7\" Super Retina XDR - 128 Go - Puce A16 Bionic",
    price: 899,
    originalPrice: 1069,
    discount: 170,
    image: "https://www.bouyguestelecom.fr/catalogue/image-resize/full/media/catalog/product/v/i/vig-apple-iphone-15-plus-noir-face.png",
    category: "Smartphones",
    merchant: "FNAC",
    condition: "new",
    operatingSystem: "iOS",
    color: "Noir",
    storage: "128 Go",
    shipping: "Livraison gratuite",
    rating: 4.7,
    reviewCount: 386,
    inStock: true,
    productUrl: "https://www.apple.com/fr/iphone-15-plus/"
  },
  {
    id: "example-11",
    ean: "1092837465001",
    title: "Samsung Galaxy S22 Ultra - 256 Go - Bordeaux - Reconditionné",
    trademark: "Samsung",
    description: "Galaxy S22 Ultra reconditionné - Grade A - écran 6,8\" Dynamic AMOLED 2X - 256 Go - S Pen inclus",
    price: 599,
    originalPrice: 1099,
    discount: 500,
    image: "https://images.samsung.com/is/image/samsung/p6pim/fr/sm-s908bdrgeub/gallery/fr-galaxy-s22-ultra-s908-sm-s908bdrgeub-530750523",
    category: "Smartphones",
    merchant: "CertiDeal",
    condition: "refurbished",
    operatingSystem: "Android",
    color: "Bordeaux",
    storage: "256 Go",
    shipping: "Livraison gratuite",
    rating: 4.5,
    reviewCount: 324,
    isEcoFriendly: true,
    inStock: true,
    productUrl: "https://www.certideal.com/fr/samsung-galaxy-s22-ultra-reconditionne"
  },
  {
    id: "example-12",
    ean: "1092837465002",
    title: "Motorola Edge 40 Pro - 256 Go - Noir",
    trademark: "Motorola",
    description: "Motorola Edge 40 Pro - écran 6,67\" pOLED 165 Hz - Snapdragon 8 Gen 2 - 256 Go",
    price: 599,
    originalPrice: 899,
    discount: 300,
    image: "https://mobilecontent.costco.com/live/resource/img/ca-static-pages/d-motorola-edge-40-pro-cosmic.jpg",
    category: "Smartphones",
    merchant: "Cdiscount",
    condition: "new",
    operatingSystem: "Android",
    color: "Noir",
    storage: "256 Go",
    shipping: "Livraison en 24h",
    rating: 4.4,
    reviewCount: 112,
    inStock: true,
    productUrl: "https://www.motorola.fr/smartphones-motorola-edge-40-pro/p"
  }
];
